# Generated by Django 5.1.7 on 2025-04-02 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_vacancy_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='position',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='api.position'),
        ),
    ]
