# Generated by Django 5.1.7 on 2025-04-02 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_vacancy_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='api.position'),
        ),
    ]
