# Generated by Django 5.2 on 2025-04-06 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_vacancy_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='position',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
